name: TEST

on:
    workflow_dispatch:
    push:

jobs:
    send-email:
        runs-on: ubuntu-latest

        steps:
            - name: Emailer Action
              uses: RubenDguez/emailer@v0.1.1-alpha
              with:
                secrets_user: ${{ secrets.USER }}
                secrets_pass: ${{ secrets.PASS }}
                from: "ADMIN"
                to: argenis.dominguez@hotmail.com
                subject: Hello There
                html: <div><h1>Hello</h1></div>
